export const dict = {
  'home' : 'خانه',
  'name' : 'نام و نام خانوادگی ',
  'login' : 'ورود',
  'username' :  'نام کاربری ',
  'password' : 'رمز عبور ',
  'password_confirmation': 'تکرار رمز عبور',
  'mobile' : 'شماره موبایل ',
  'error': 'خطا',
  'sign_in' : 'ورود ',
  'sign_up' : 'ثبت نام',
  'back' : 'بازگشت',
  'signed_up_already': 'تا کنون ثبت نام نکرده اید؟',
  'new_advert': 'درج آگهی ',
  'title': 'عنوان',
  'abstract': 'چکیده',
  'content': 'متن',
  'submit': 'ثبت ',
  'upload_from_gallery': 'انتخاب از گالری',
  'welcome': 'خوش آمدید',
  'sign_out': 'خروج',
  'phone_number': 'شماره تلفن',
  'telegram_channel': 'کانال تلگرام',
  'instagram_page': 'صفحه اینستاگرام',
  'address': 'آدرس ',
  'email': 'ایمیل ',
  'contact_information':'اطلاعات تماس ',
  'search': 'جستجو ',
  'cancel' : 'انصراف',
  'view': 'نمایش',
  'edit': 'ویرایش',
  'delete': 'حذف',
  'adverts_nes': 'عنوان، متن و شماره تلفن اجباری است',
  'my_pins': ' نشان شده‌ها ',
  'pin' : 'نشان کن',
  'pinned': 'نشان شده',
  'message_to_seller': 'ارسال پیام',
  'messages': 'پیام ها ',
  'send_message': 'پیام خود را بنویسید',
  'province': 'استان',
  'city': 'شهر',
  'website': 'وبسایت',
  'call': 'تماس بگیرید',
  'ago': ' قبل',
  'all_above': 'همه ی موارد فوق',
  'no_result': 'موردی یافت نشد ',
  'category': 'دسته بندی ',
  'leg':'مسیر',
  'date':'تاریخ',
  'time': 'زمان',
  'numberOfPassngers': 'تعداد مسافران ',
  'surename': 'نام خانوادگی',
  'fathername':'نام پدر',
  'ssn':'کدملی',
  'birthplace':'محل تولد',
  'pass_no': 'شماره گذرنامه',
  'birthdate': 'تاریخ تولد',
  'place_of_birth': 'محل تولد',
  'required_fields': 'فیلدهای اجباری',
  'en_father_name': 'نام پدر لاتین',
  'en_name': 'نام لاتین',
  'en_surename': 'نام خانوادگی لاتین ',
  'passport_no': 'شماره گذرنامه',
  'final_confirm' : 'تایید نهایی ',
  'document_form': 'فرم اسناد ',
  'save': 'ذخیره',
  'documents':'اسناد ',
  'type' : 'نوع',
  'string': 'متن کوتاه',
  'text': 'متن بلند',
  'select': 'گزینه',
  'multiSelect': 'چند گزینه',
  'table': 'جدول',
  'date':'تاریخ',
  'refundable': 'قابل اعاده',
  'yes':'بله',
  'no':'خیر',
  'commentable':'قابل نظردهی',
  'end_point':'نقطه پایان',
  'start_point':'نقطه شروع',
  'votable':'رای گیری',
  'publishable':'قابل انتشار',
  'field_name': 'نام فیلد',
  'add': 'افزودن ',
  'remove': 'حذف',
  'auxiliary_tables': 'جداول کمکی',
  'create_by':'ایجاد شده توسط',
  'list': 'لیست',
  'workflows': 'گردش کارها',
  'auxiliary_records': 'مقادیر کمکی',
  'basic_table': 'جدول پایه',
  'relation_table': 'جدول رابطه',
  'auxiliary_table_form': 'فرم جدول کمکی ' ,
  'Basic': 'پایه',
  'Relation': 'رابطه ',
  'Divan': 'دیوان',
  'workflow_form':'فرم گردش کار',
  'submitting':'در حال ارسال ... ',
  'settings':'تنظیمات',
  'receiving':'در حال دریافت ...',
  'workflow_tables': 'جداول کمکی گردش کار ',
  'auxiliary_table': 'جدول کمکی',
  'workflow':'گردش کار',
  'actions' : 'عملیات',
  'roles': 'نقش ها',
  'divan': 'دیوان',
  'enter_your_email': 'ایمیل خود را وارد کنید',
  'enter_your_password': 'رمز عبور را وارد کنید ',
  'enter_your_password_confirmation': 'رمز عبور را تکرار کنید ',
  'profiles': 'افراد ',
  'firstname': 'نام',
  'if_registered': 'اگر قبلا ثبت نام کرده اید',
  'you_can_login':'وارد شوید ',
  'if_not_registered': 'اگر ثبت نام نکرده اید',
  'you_can_sign_up':'ثبت نام کنید',
  'new_assignment': 'اعطای نقش جدید',
  'posts': 'پست ها',
  'bookmark': 'نشان',
  'like':'علاقه',
  'follow':'دنبال',
  'share':'اشتراک',
  'social_acts':'عملگرهای اجتماعی ',
  'channels': 'کانال ها',
  'close': 'بستن',
  'channel':'کانال ',
  'details': 'شرح',
  'Shoa': 'شعاع ',
  'role': 'نقش',
  'Default': 'پیش فرض',
  'NonDefault':'غیر پیش فرض ',
  'value': ' مقدار',
  'true': 'مثبت',
  'false': 'منفی',
  'access_control_list':'لیست کنترل دسترسی',
  'access_control_form':'فرم کنترل دسترسی',
  'assignment_form':'فرم اعطای نقش',
  'comment_form': 'نظر بدهید',
  'post_form': 'فرم پست',
  'metas':'پیش جداول',
  'shoa': 'شعاع',
  'form' : 'ورود اطلاعات',
  'choose_image': 'انتخاب عکس',
  'logout': 'خروج',
  'more': 'بیشتر ...',
  'social': 'اجتماعی',
  'courses':'دروس',
  'discussions':'گفتگو ها',
  'exams':'آزمون ها ',
  'public':'عمومی',
  'private':'خصوصی ',
  'course_type':'نوع درس',
  'select_appropriate_title': 'عنوانی مناسب انتخاب کنید',
  'write_appropriate_description':'شرحی از اهداف و روش ها بنویسید',
  'description':'شرح ',
  'drag_or_browse': 'فایل مورد نظر را اینجا بیاندازید یا کلیک کنید',
  'attachment' : 'فایل های پیوست',
  'tasks': 'وظایف',
  'start_date': 'تاریخ شروع',
  'deadline' : 'مهلت نهایی',
  'select_a_date' : 'یک تاریخ انتخاب کنید',
  'incomplete_data': 'همه ی موارد را تکمیل کنید',
  'alert': 'هشدار',
  'deadline_time': 'ساعت',
  'start_time':'ساعت',
  'select_a_time':'انتخاب ساعت',
  'coworkers': 'همکاران',
  'works': 'کارها ',
  'dashboard':'میزکار',
  'tavan':'توان',
  'statuses': 'وضعیت ها',
  'status' : 'وضعیت',
  'add_stauts': 'تغییر وضعیت',
  'select' : 'انتخاب',
  'new': 'جدید',
  'task' : 'وظیفه',
  'attachments': 'پیوست ها',
  'reports': 'اسناد و گزارشات',
  'tags':'برچسب ها',
  'new_tag': 'برچسب جدید ',
  'recent_tasks': 'وظایف اخیر',
  'public_tasks': 'وظایف عمومی',
  'sort_by' : 'مرتب سازی',
  'by_title':'عنوان',
  'by_events':'رخداد',
  'deadline_near': 'مهلت نهایی نزدیک',
  'new_report': 'گزارش جدید',
  'new_comments': 'گفتگوی جدید',
  'Admin':'مدیر',
  'Colleague':'همکار',
  'Observer':'ناظر',
  'Creator':'سازنده',
  'verification_code':'کد احراز',
  'enter_verification_code':  'کد احراز را وارد کنید',
  'your_tasks':'وظایف مرتبط با شما',
  'your_newest_works':'جدیدترین کارهای مرتبط با شما',
  'todo_list': 'تقسیم بندی کار',
  'todo_participants': 'افراد',
  'new_todo_participants': 'افراد جدید',
  'not_found': 'چیزی یافت نشد',
  'are_you_sure': 'مطمئن هستید؟',
  'Confirmer': 'تایید کننده',
  'time_sheets': 'جداول زمان کار',
  'morning_report':'گزارش پیش از ظهر',
  'afternoon_report':'گزارش بعد از ظهر',
  'extra_report':'گزارش اضافه کاری',
  'write_appropriate_details':'شرحی کامل بنویسید',
  'associations':'مرتبط با',
  'sheet_date':'تاریخ جدول'
};
