export const dict = {
  'home' : 'خانه',
  'name' : 'نام و نام خانوادگی ',
  'login' : 'ورود',
  'username' :  'نام کاربری ',
  'password' : 'رمز عبور ',
  'password_confirmation': 'تکرار رمز عبور',
  'mobile' : 'شماره موبایل ',
  'error': 'خطا',
  'sign_in' : 'ورود ',
  'sign_up' : 'ثبت نام',
  'back' : 'بازگشت',
  'signed_up_already': 'تا کنون ثبت نام نکرده اید؟',
  'new_advert': 'درج آگهی ',
  'title': 'عنوان',
  'abstract': 'چکیده',
  'content': 'متن',
  'submit': 'ثبت ',
  'upload_from_gallery': 'انتخاب از گالری',
  'welcome': 'خوش آمدید',
  'sign_out': 'خروج',
  'phone_number': 'شماره تلفن',
  'telegram_channel': 'کانال تلگرام',
  'instagram_page': 'صفحه اینستاگرام',
  'address': 'آدرس ',
  'email': 'ایمیل ',
  'contact_information':'اطلاعات تماس ',
  'search': 'جستجو ',
  'cancel' : 'بیخیال',
  'view': 'نمایش',
  'edit': 'ویرایش',
  'delete': 'حذف',
  'adverts_nes': 'عنوان، متن و شماره تلفن اجباری است',
  'my_pins': ' نشان شده‌ها ',
  'pin' : 'نشان کن',
  'pinned': 'نشان شده',
  'message_to_seller': 'ارسال پیام',
  'messages': 'پیام ها ',
  'send_message': 'پیام خود را بنویسید',
  'province': 'استان',
  'city': 'شهر',
  'website': 'وبسایت',
  'call': 'تماس بگیرید',
  'ago': 'قبل ',
  'all_above': 'همه ی موارد فوق',
  'no_result': 'موردی یافت نشد ',
  'category': 'دسته بندی ',
  'leg':'مسیر',
  'date':'تاریخ',
  'time': 'زمان',
  'numberOfPassngers': 'تعداد مسافران ',
  'surename': 'نام خانوادگی',
  'fathername':'نام پدر',
  'ssn':'کدملی',
  'birthplace':'محل تولد',
  'pass_no': 'شماره گذرنامه',
  'birthdate': 'تاریخ تولد',
  'place_of_birth': 'محل تولد',
  'required_fields': 'فیلدهای اجباری',
  'en_father_name': 'نام پدر لاتین',
  'en_name': 'نام لاتین',
  'en_surename': 'نام خانوادگی لاتین ',
  'passport_no': 'شماره گذرنامه',
  'final_confirm' : 'تایید نهایی ',
  'document_form': 'فرم اسناد ',
  'save': 'ذخیره',
  'documents':'اسناد ',
  'type' : 'نوع',
  'string': 'متن کوتاه',
  'text': 'متن بلند',
  'select': 'گزینه',
  'multiSelect': 'چند گزینه',
  'table': 'جدول',
  'date':'تاریخ',
  'refundable': 'قابل اعاده',
  'yes':'بله',
  'no':'خیر',
  'commentable':'قابل نظردهی',
  'end_point':'نقطه پایان',
  'start_point':'نقطه شروع',
  'votable':'رای گیری',
  'publishable':'قابل انتشار',
  'field_name': 'نام فیلد',
  'add': 'افزودن ',
  'remove': 'حذف',
  'auxiliary_tables': 'جداول کمکی',
  'create_by':'ایجاد شده توسط',
  'list': 'لیست',
  'workflows': 'گردش کارها',
  'auxiliary_records': 'مقادیر کمکی',
  'basic_table': 'جدول پایه',
  'relation_table': 'جدول رابطه',
  'auxiliary_table_form': 'فرم جدول کمکی ' ,
  'Basic': 'پایه',
  'Relation': 'رابطه ',
  'Divan': 'دیوان',
  'workflow_form':'فرم گردش کار',
  'submitting':'در حال ارسال ... ',
  'settings':'تنظیمات',
  'receiving':'در حال دریافت ...',
  'workflow_tables': 'جداول کمکی گردش کار ',
  'auxiliary_table': 'جدول کمکی',
  'workflow':'گردش کار',
  'actions' : 'عملیات',
  'roles': 'نقش ها',
  'divan': 'دیوان',
  'enter_your_email': 'ایمیل خود را وارد کنید',
  'enter_your_password': 'رمز عبور را وارد کنید ',
  'enter_your_password_confirmation': 'رمز عبور را تکرار کنید ',
  'profiles': 'افراد ',
  'firstname': 'نام',
  'if_registered': 'اگر قبلا ثبت نام کرده اید',
  'you_can_login':'وارد شوید ',
  'if_not_registered': 'اگر ثبت نام نکرده اید',
  'you_can_sign_up':'ثبت نام کنید',
  'new_assignment': 'اعطای نقش جدید',
  'posts': 'پست ها'
};
